-- MySQL Script generated by MySQL Workbench
-- 12/15/14 08:21:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema logins
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema logins
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `logins` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `logins` ;

-- -----------------------------------------------------
-- Table `logins`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logins`.`users` ;

CREATE TABLE IF NOT EXISTS `logins`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
